### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by dianjuar** [mrmlnc/material-shadows#8]
I saw this repo very usefull. Do you have plans to submit it in the npm directory ???

The updates in it will be easy to follow and apply

**Comment by mrmlnc** [comment]
Hello, @dianjuar,

What do you mean? You can install this repository from npm by `npm i material-shadows`.

**Comment by dianjuar** [comment]
OH! so sorry. It was there in the Readme...

Maybe, I didn't find it because the repo doesn't have those cool stickers of npm.

Thanks for taking your time in this dumb question.
